/*******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Write and read from EEPROM through I2C
 ******************************************************************************/

#include "gpio_interface.h"
#include "rcc_interface.h"
#include "i2c_interface.h"
#include "eeprom_interface.h"

/*******************************************************************************
 * Global variables
 ******************************************************************************/

static I2C_Config_t configI2C;

static void MCAL_Init(void);

int main(void)
{
	MCAL_Init();
	
	/* Initialization of EEPROM */
	HAL_EEPROM_Void_Init();
	
		/************************ Test Case 1 ************************/
	uint8_t Ch1[7] = {0x01,0x02,0x03,0x04,0x05,0x06,0x07};
	uint8_t Ch2[7] = {0};

	HAL_EEPROM_U8_WriteNBytes(&configI2C, 0xAF, Ch1, 7);
	HAL_EEPROM_U8_ReadNBytes(&configI2C,0xAF, Ch2, 7);

	/************************ Test Case 2 ************************/
	Ch1[0] = 0xA;
	Ch1[1] = 0xB;
	Ch1[2] = 0xC;
	Ch1[3] = 0xD;

	HAL_EEPROM_U8_WriteNBytes(&configI2C, 0xFFF, Ch1, 4);
	HAL_EEPROM_U8_ReadNBytes(&configI2C,0xFFF, Ch2, 4);

	/* Loop forever */
	while(TRUE)
	{
	}

	return 0;
}

static void MCAL_Init(void)
{
	/* Clock Enable */
	MCAL_RCC_Void_EnableClock(RCC_APB2_BUS, RCC_APB2_PERIPHERAL_EN_IOPBEN);
	MCAL_RCC_Void_EnableClock(RCC_APB2_BUS, RCC_APB2_PERIPHERAL_EN_AFIOEN);
	MCAL_RCC_Void_EnableClock(RCC_APB1_BUS, RCC_APB1_PERIPHERAL_EN_I2C1EN);

	/* I2C GPIO configuration */
	GPIO_PinConfig_t configPinI2C = {GPIO_PIN_6, GPIO_MODE_OUTPUT_AF_OD, GPIO_SPEED_2M};
	MCAL_GPIO_Init(GPIOB, &configPinI2C);
	configPinI2C.GPIO_PinNumber = GPIO_PIN_7;
	MCAL_GPIO_Init(GPIOB, &configPinI2C);

	/* I2C configuration */
	configI2C.I2Cx = I2C1;
	configI2C.clockSpeed = 100000;
	configI2C.stretchMode = I2C_StretchMode_Enable;
	configI2C.generalCall = I2C_GeneralCall_Enable;
	configI2C.speed = I2C_Speed_standardMode;
	configI2C.mode = I2C_Mode_I2C;
	configI2C.ackControl = I2C_AcknowledgeControl_Enable;
	configI2C.IRQEnable = I2C_IRQEnable_Disable;
	configI2C.pSlaveCallBack = NULL;

	MCAL_I2C_Void_Init(&configI2C);

	return ;
}
