/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include "gpio_interface.h"
#include "lcd_interface.h"
#include "exti_interface.h"
#include "nvic_interface.h"

static uint8 IRQNumber = 0;
static uint8 countChangedFlag = 1;

static void delay_ms(uint32 time);
static void EXTI9_Callback(void);

int main(void)
{
	/* Clock Enable */
	RCC_GPIOA_CLK_EN();
	RCC_GPIOB_CLK_EN();

	/* EXTI Configuration */
	EXTI_PinConfig_t EXTIConfig;
	EXTIConfig.Pin.InputLineNumber = EXTI_LINE9;
	EXTIConfig.Pin.GPIOx = GPIOB;
	EXTIConfig.Pin.GPIOPin = GPIO_PIN_9;
	EXTIConfig.TriggerCase = EXTI_FALLING;
	EXTIConfig.Ptr_IRQCallBack = EXTI9_Callback;
	EXTIConfig.IRQEnabled = EXTI_IRQ_ENABLE;

	/* MCAL initializations */
	MCAL_EXTI_Void_Init(&EXTIConfig);
	MCAL_NVIC_Void_EnableIRQ(EXTI9_5_IRQn);

	/* HAL initializations */
	HAL_LCD_Void_Init();

	HAL_LCD_Void_WriteString((uint8 *) "EXTI9 served: ");
	HAL_LCD_Void_GoTo(1, 0);
	HAL_LCD_Void_WriteString((uint8 *) "Time(s)");

	/* Loop forever */
	while(TRUE)
	{
		if(countChangedFlag == 1)
		{
			countChangedFlag = 0;
			HAL_LCD_Void_GoTo(0, 13);
			/* 8-bit counter never exceeds 3 digit places hence 3-spaces */
			HAL_LCD_Void_WriteString((uint8 *) "   ");
			/* Column 13 since the text before count is 14 */
			HAL_LCD_Void_GoTo(0, 14);
			HAL_LCD_Void_WriteNumber(IRQNumber);
			delay_ms(100);
		}
		else
		{
		}
	}

	return 0;
}

static void delay_ms(uint32 time)
{
	vuint32 i;

	while(0 != time--)
	{
		for(i = 0; i < 0xff ; i++);
	}

	return;
}


static void EXTI9_Callback(void)
{
	++IRQNumber;
	countChangedFlag = 1;
}
