/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include "gpio_interface.h"

static void my_wait(uint32 t);

int main(void)
{
	/* Clock Enable */

	RCC_GPIOA_CLK_EN();
	RCC_GPIOB_CLK_EN();

	/* GPIO init */
	GPIO_PinConfig_t pinCfg;

	/* PA1 input high Z */
	pinCfg.GPIO_PinNumber = GPIO_PIN_1;
	pinCfg.GPIO_MODE = GPIO_MODE_INPUT_FLO;
	MCAL_GPIO_Init(GPIOA, &pinCfg);

	/* PA13 input high-Z */
	pinCfg.GPIO_PinNumber = GPIO_PIN_13;
	pinCfg.GPIO_MODE = GPIO_MODE_INPUT_FLO;
	MCAL_GPIO_Init(GPIOA, &pinCfg);

	/* PBl output push-pull mode */
	/* CNF  00: General purpose output push-pull */
	/* MODE 01: Output mode, max speed 10 MHZ */
	pinCfg.GPIO_PinNumber = GPIO_PIN_1;
	pinCfg.GPIO_MODE = GPIO_MODE_OUTPUT_PP;
	pinCfg.GPIO_OUTPUT_SPEED = GPIO_SPEED_10M;
	MCAL_GPIO_Init(GPIOB, &pinCfg);

	/* PB13 output push-pull mode */
	/* CNF  00: General purpose output push-pull */
	/* MODE 01: Output mode, max speed 10 MHZ */
	pinCfg.GPIO_PinNumber = GPIO_PIN_13;
	pinCfg.GPIO_MODE = GPIO_MODE_OUTPUT_PP;
	pinCfg.GPIO_OUTPUT_SPEED = GPIO_SPEED_10M;
	MCAL_GPIO_Init(GPIOB, &pinCfg);

    /* Loop forever */
	while(TRUE)
	{
		if(MCAL_GPIO_ReadPin(GPIOA, GPIO_PIN_1) == GPIO_PIN_RESET) /* press */
		{
			MCAL_GPIO_TogglePin(GPIOB, GPIO_PIN_1);
			while(MCAL_GPIO_ReadPin(GPIOA, GPIO_PIN_1) == GPIO_PIN_RESET); /* Single press */
		}

		if(MCAL_GPIO_ReadPin(GPIOA, GPIO_PIN_13) == GPIO_PIN_SET) /* Multi presses */
		{
			MCAL_GPIO_TogglePin(GPIOB, GPIO_PIN_13);
		}

		my_wait(1);
	}

	return 0;
}

static void my_wait(uint32 t)
{
	vuint32 i,j;

	for (i = 0; i < t; i++)
	{
		for(j = 0; j < 0xff ; j++);
	}

	return;
}
